### ISSUE TITLE
HTML component flickers when "move with transform" is enabled.

### ISSUE THREAD

**Issue by hccampos** [GooTechnologies/goojs#9]
The HTML component rounds the transform position when "move with transform" is enabled. This causes flickering when moving objects or the camera around.

**Comment by schteppe** [comment]
Started working on this here: https://github.com/GooTechnologies/goojs/compare/optional-html-integer-positioning

**Comment by schteppe** [comment]
Fixed!

https://github.com/GooTechnologies/goojs/commit/cde7f780f6a3ef1e575ef98c81ce42046bf2298b https://github.com/GooTechnologies/goojs/commit/e8c1a42a920215f580da4ffce002781d74040074
